##===- projects/sample/lib/Makefile ------------------------*- Makefile -*-===##

#
# Relative path to the top of the source tree.
#
LEVEL=..

#
# List all of the subdirectories that we will compile.
#
DIRS= FullIFDuplica ParIFDuplica InsDuplica
#ShortcutDetector
include $(LEVEL)/Makefile.common
